[toolchain]
channel = "nightly-2024-11-20" # This should track the version specified in https://docs.rs/about/builds to make sure the docs build correctly.
components = [
  "rustc",
  "cargo",
  "rustfmt",
  "rust-std",
  "clippy",
  "rust-src",
  "rust-analysis",
]
